version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-player-sdk
    docker:
      - image: circleci/node:12.13.0-browsers
    steps:
      - checkout:
          path: ~/sunbird-player-sdk
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: cd projects/sunbird-player-sdk && sudo npm install
      - run: sudo npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: 
          name: Install sonar scanner
          command: 'sudo npm install -i -g sonarqube-scanner'
      - run: 
          name: Sonar scanner
          command: sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-player-sdk -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=ts -Dsonar.sources=projects/sunbird-player-sdk/src -Dsonar.typescript.lcov.reportPaths=coverage/sunbird-player-sdk/lcov.info
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
